import { 
  Book, Heart, Star, Bookmark, FileText, GraduationCap,
  Lightbulb, Globe, Users, Briefcase, Code, Music,
  Camera, Palette, Coffee, Plane, Home, Car, Leaf,
  Mountain, Sunrise, Moon, Sun, Cloud, Droplet, Flame,
  Zap, Shield, Award, Trophy, Target, Compass, Map,
  Clock, Calendar, Bell, Gift, Crown, Diamond, Gem,
  Sparkles, Wand2, Brain, Atom, Microscope, Telescope,
  Rocket, Cpu, Monitor, Smartphone, Tablet, Tv, Radio,
  Headphones, Speaker, Mic, Video, Film, Clapperboard,
  Gamepad2, Puzzle, Dices, Drama, Theater, Ticket,
  Utensils, ChefHat, Wine, Pizza, IceCream, Cake, Apple,
  Carrot, Wheat, Flower, TreeDeciduous, Trees, Tent, Umbrella,
  Anchor, Ship, Truck, Bus, Train, Bike,
  Footprints, Dog, Cat, Bird, Fish, Bug, Rabbit, Squirrel,
  Baby, User, UserPlus, UserCheck, Building, Building2, Church,
  Castle, School, Library, Store, Factory, Warehouse,
  Hammer, Wrench, Scissors, PenTool, Brush, Eraser, Ruler,
  Scale, Gavel, FileCheck, FileX, FilePlus, FolderOpen,
  Archive, Database, Server, HardDrive, Wifi, Bluetooth,
  Battery, Power, Plug, Lamp, Fan, Thermometer, Stethoscope,
  Pill, Syringe, Activity, HeartPulse, Bone, Eye,
  Ear, Hand, Fingerprint,
  Lock, Unlock, Key, KeyRound, ShieldCheck, ShieldAlert,
  AlertTriangle, AlertCircle, Info, HelpCircle, MessageCircle,
  MessageSquare, Mail, AtSign, Phone, PhoneCall, Send,
  Download, Upload, Share, Link, ExternalLink, Copy,
  ClipboardList, ClipboardCheck, Search, ZoomIn, ZoomOut,
  Filter, SortAsc, SortDesc, LayoutGrid, LayoutList, Columns,
  Rows, Table2, PieChart, BarChart, LineChart, TrendingUp,
  TrendingDown, DollarSign, Euro, PoundSterling, Bitcoin,
  BookOpen, FlaskConical, PenLine, Landmark, Laptop, Languages, Calculator, Dumbbell, BookHeart
} from 'lucide-react';

// Complete icon map with all icons
export const CATEGORY_ICON_MAP: Record<string, any> = {
  'book': Book,
  'book-open': BookOpen,
  'book-heart': BookHeart,
  'heart': Heart,
  'star': Star,
  'bookmark': Bookmark,
  'file-text': FileText,
  'graduation-cap': GraduationCap,
  'lightbulb': Lightbulb,
  'globe': Globe,
  'users': Users,
  'briefcase': Briefcase,
  'code': Code,
  'music': Music,
  'camera': Camera,
  'palette': Palette,
  'coffee': Coffee,
  'plane': Plane,
  'home': Home,
  'car': Car,
  'leaf': Leaf,
  'mountain': Mountain,
  'sunrise': Sunrise,
  'moon': Moon,
  'sun': Sun,
  'cloud': Cloud,
  'droplet': Droplet,
  'flame': Flame,
  'zap': Zap,
  'shield': Shield,
  'award': Award,
  'trophy': Trophy,
  'target': Target,
  'compass': Compass,
  'map': Map,
  'clock': Clock,
  'calendar': Calendar,
  'bell': Bell,
  'gift': Gift,
  'crown': Crown,
  'diamond': Diamond,
  'gem': Gem,
  'sparkles': Sparkles,
  'wand': Wand2,
  'brain': Brain,
  'atom': Atom,
  'microscope': Microscope,
  'telescope': Telescope,
  'rocket': Rocket,
  'cpu': Cpu,
  'monitor': Monitor,
  'smartphone': Smartphone,
  'tablet': Tablet,
  'tv': Tv,
  'radio': Radio,
  'headphones': Headphones,
  'speaker': Speaker,
  'mic': Mic,
  'video': Video,
  'film': Film,
  'clapperboard': Clapperboard,
  'gamepad': Gamepad2,
  'puzzle': Puzzle,
  'dices': Dices,
  'drama': Drama,
  'theater': Theater,
  'ticket': Ticket,
  'utensils': Utensils,
  'chef-hat': ChefHat,
  'wine': Wine,
  'pizza': Pizza,
  'ice-cream': IceCream,
  'cake': Cake,
  'apple': Apple,
  'carrot': Carrot,
  'wheat': Wheat,
  'flower': Flower,
  'tree': TreeDeciduous,
  'trees': Trees,
  'tent': Tent,
  'umbrella': Umbrella,
  'anchor': Anchor,
  'ship': Ship,
  'truck': Truck,
  'bus': Bus,
  'train': Train,
  'bike': Bike,
  'footprints': Footprints,
  'dog': Dog,
  'cat': Cat,
  'bird': Bird,
  'fish': Fish,
  'bug': Bug,
  'rabbit': Rabbit,
  'squirrel': Squirrel,
  'baby': Baby,
  'user': User,
  'user-plus': UserPlus,
  'user-check': UserCheck,
  'building': Building,
  'building2': Building2,
  'church': Church,
  'castle': Castle,
  'school': School,
  'library': Library,
  'store': Store,
  'factory': Factory,
  'warehouse': Warehouse,
  'hammer': Hammer,
  'wrench': Wrench,
  'scissors': Scissors,
  'pen-tool': PenTool,
  'pen-line': PenLine,
  'brush': Brush,
  'eraser': Eraser,
  'ruler': Ruler,
  'scale': Scale,
  'gavel': Gavel,
  'file-check': FileCheck,
  'file-x': FileX,
  'file-plus': FilePlus,
  'folder-open': FolderOpen,
  'archive': Archive,
  'database': Database,
  'server': Server,
  'hard-drive': HardDrive,
  'wifi': Wifi,
  'bluetooth': Bluetooth,
  'battery': Battery,
  'power': Power,
  'plug': Plug,
  'lamp': Lamp,
  'fan': Fan,
  'thermometer': Thermometer,
  'stethoscope': Stethoscope,
  'pill': Pill,
  'syringe': Syringe,
  'activity': Activity,
  'heart-pulse': HeartPulse,
  'bone': Bone,
  'eye': Eye,
  'ear': Ear,
  'hand': Hand,
  'fingerprint': Fingerprint,
  'lock': Lock,
  'unlock': Unlock,
  'key': Key,
  'key-round': KeyRound,
  'shield-check': ShieldCheck,
  'shield-alert': ShieldAlert,
  'alert-triangle': AlertTriangle,
  'alert-circle': AlertCircle,
  'info': Info,
  'help-circle': HelpCircle,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'mail': Mail,
  'at-sign': AtSign,
  'phone': Phone,
  'phone-call': PhoneCall,
  'send': Send,
  'download': Download,
  'upload': Upload,
  'share': Share,
  'link': Link,
  'external-link': ExternalLink,
  'copy': Copy,
  'clipboard-list': ClipboardList,
  'clipboard-check': ClipboardCheck,
  'search': Search,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  'filter': Filter,
  'sort-asc': SortAsc,
  'sort-desc': SortDesc,
  'layout-grid': LayoutGrid,
  'layout-list': LayoutList,
  'columns': Columns,
  'rows': Rows,
  'table': Table2,
  'pie-chart': PieChart,
  'bar-chart': BarChart,
  'line-chart': LineChart,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'dollar': DollarSign,
  'euro': Euro,
  'pound': PoundSterling,
  'bitcoin': Bitcoin,
  'flask': FlaskConical,
  'landmark': Landmark,
  'laptop': Laptop,
  'languages': Languages,
  'calculator': Calculator,
  'dumbbell': Dumbbell,
};

// Get gradient style based on icon or color class
export const getGradientStyle = (icon: string, colorClass?: string): string => {
  // If a color class is provided, convert it to gradient
  if (colorClass) {
    if (colorClass.includes('gradient')) {
      // Already a gradient class, convert to CSS
      const gradientMap: Record<string, string> = {
        'bg-gradient-to-r from-orange-500 to-pink-500': 'linear-gradient(to right, #f97316, #ec4899)',
        'bg-gradient-to-r from-cyan-500 to-blue-500': 'linear-gradient(to right, #06b6d4, #3b82f6)',
        'bg-gradient-to-r from-green-500 to-teal-500': 'linear-gradient(to right, #22c55e, #14b8a6)',
        'bg-gradient-to-r from-purple-500 to-pink-500': 'linear-gradient(to right, #a855f7, #ec4899)',
        'bg-gradient-to-r from-yellow-400 to-orange-500': 'linear-gradient(to right, #facc15, #f97316)',
        'bg-gradient-to-r from-slate-400 to-slate-600': 'linear-gradient(to right, #94a3b8, #475569)',
        'bg-gradient-to-r from-indigo-600 to-purple-600': 'linear-gradient(to right, #4f46e5, #9333ea)',
        'bg-gradient-to-r from-red-500 to-orange-500': 'linear-gradient(to right, #ef4444, #f97316)',
      };
      return gradientMap[colorClass] || 'linear-gradient(135deg, #06B6D4, #0891B2)';
    }
    
    // Solid color class to gradient
    const colorToGradient: Record<string, string> = {
      'bg-red-500': 'linear-gradient(135deg, #ef4444, #dc2626)',
      'bg-orange-500': 'linear-gradient(135deg, #f97316, #ea580c)',
      'bg-yellow-500': 'linear-gradient(135deg, #eab308, #ca8a04)',
      'bg-green-500': 'linear-gradient(135deg, #22c55e, #16a34a)',
      'bg-teal-500': 'linear-gradient(135deg, #14b8a6, #0d9488)',
      'bg-cyan-500': 'linear-gradient(135deg, #06b6d4, #0891b2)',
      'bg-blue-500': 'linear-gradient(135deg, #3b82f6, #2563eb)',
      'bg-indigo-500': 'linear-gradient(135deg, #6366f1, #4f46e5)',
      'bg-purple-500': 'linear-gradient(135deg, #a855f7, #9333ea)',
      'bg-pink-500': 'linear-gradient(135deg, #ec4899, #db2777)',
      'bg-emerald-500': 'linear-gradient(135deg, #10b981, #059669)',
      'bg-amber-700': 'linear-gradient(135deg, #b45309, #92400e)',
      'bg-primary': 'linear-gradient(135deg, #06B6D4, #0891B2)',
    };
    return colorToGradient[colorClass] || 'linear-gradient(135deg, #06B6D4, #0891B2)';
  }

  // Fallback to icon-based gradients
  const gradientMap: Record<string, string> = {
    'graduation-cap': 'linear-gradient(135deg, #10B981, #059669)',
    'flask': 'linear-gradient(135deg, #3B82F6, #06B6D4)',
    'book-open': 'linear-gradient(135deg, #06B6D4, #0891B2)',
    'target': 'linear-gradient(135deg, #EF4444, #DC2626)',
    'landmark': 'linear-gradient(135deg, #F59E0B, #D97706)',
    'laptop': 'linear-gradient(135deg, #06B6D4, #0891B2)',
    'moon': 'linear-gradient(135deg, #F59E0B, #D97706)',
    'baby': 'linear-gradient(135deg, #EC4899, #DB2777)',
    'book': 'linear-gradient(135deg, #06B6D4, #0891B2)',
    'brain': 'linear-gradient(135deg, #8B5CF6, #7C3AED)',
    'book-heart': 'linear-gradient(135deg, #10B981, #059669)',
    'trending-up': 'linear-gradient(135deg, #F97316, #EA580C)',
    'heart': 'linear-gradient(135deg, #EC4899, #DB2777)',
    'stethoscope': 'linear-gradient(135deg, #EF4444, #DC2626)',
    'languages': 'linear-gradient(135deg, #14B8A6, #0D9488)',
    'globe': 'linear-gradient(135deg, #84CC16, #65A30D)',
    'calculator': 'linear-gradient(135deg, #22C55E, #16A34A)',
    'palette': 'linear-gradient(135deg, #A855F7, #9333EA)',
    'music': 'linear-gradient(135deg, #F472B6, #EC4899)',
    'dumbbell': 'linear-gradient(135deg, #EF4444, #DC2626)',
    'pen-line': 'linear-gradient(135deg, #A855F7, #7C3AED)',
    'code': 'linear-gradient(135deg, #3B82F6, #1D4ED8)',
    'rocket': 'linear-gradient(135deg, #F97316, #EA580C)',
  };
  return gradientMap[icon] || 'linear-gradient(135deg, #06B6D4, #0891B2)';
};

// Render category icon component
export const getCategoryIcon = (iconName: string, className: string = 'w-6 h-6') => {
  const IconComponent = CATEGORY_ICON_MAP[iconName] || Book;
  return <IconComponent className={className} />;
};
